/**
 * `kei-transaction` — the umbrella package, and the default install.
 *
 *   import { Kei } from 'kei-transaction'
 *
 *   const kei = await Kei.start()          // wallet created, persisted, funded
 *   await kei.send('kei_3abc...', 0.001)   // sub-cent, instant, feeless
 *
 * Sub-packages (`@keicoin/core`, `@keicoin/tokens`, `@keicoin/claims`, `@keicoin/market`,
 * `@keicoin/work`, `@keicoin/wallet`) exist for people who care about bundle size,
 * not as a puzzle everyone must solve (SPEC §10.1).
 */

export { Kei } from './kei.js'
export type {
  ItemsNamespace,
  PayOptions,
  Receipt,
  ServerOptions,
  ShopSetup,
  StartOptions,
  TokenNamespace,
  TopUpOptions,
} from './kei.js'
export {
  assertServerOnly,
  deploymentSignal,
  isServerRuntime,
  looksLikeBrowser,
  testnetAllowedInDeployment,
} from './environment.js'
export { defaultSeedStore, describeCustody, persistSeed, readSeed, seedStoreKey } from './storage.js'
export type {
  SeedCustody,
  SeedDurability,
  SeedOrigin,
  SeedSessionReason,
  SeedStore,
  SeedWriteResult,
} from './storage.js'

// Re-export the common surface, so an integration never has to reach past the
// umbrella for a type or a helper it can see in its own editor.
export {
  ADDRESS_PREFIX,
  HttpNode,
  issuanceBurn,
  KEI_ASSET,
  KEI_DECIMALS,
  KEI_TOTAL_SUPPLY,
  KeiClient,
  KeiError,
  MAX_CHALLENGE_CONTEXT_ENTRIES,
  MAX_CHALLENGE_CONTEXT_KEY,
  MAX_CHALLENGE_CONTEXT_VALUE,
  MAX_CHALLENGE_DOMAIN,
  MockNode,
  NULL_REPRESENTATIVE,
  addressFromPublicKey,
  createNonceStore,
  isAddress,
  isSeed,
  keyPairFromSeed,
  mockRpcHandler,
  ownershipChallengeHash,
  parseAccountSwaps,
  parseOwnershipChallenge,
  parseSwapInfo,
  parseSwapOffer,
  publicKeyFromAddress,
  randomChallengeNonce,
  randomSalt,
  randomSeed,
  verifyOwnershipProof,
} from '@keicoin/core'
export type {
  AccountInfo,
  AssetId,
  AssetInfo,
  Block,
  ChallengeContextValue,
  ClientEvents,
  CommitInfo,
  Holding,
  HttpNodeOptions,
  KeiNode,
  KeyPair,
  MockRpcOptions,
  NetworkName,
  NonceStore,
  OwnershipChallenge,
  OwnershipChallengeMessage,
  OwnershipExpectation,
  OwnershipProof,
  PaymentEvent,
  Receivable,
  RevealPolicy,
  Role,
  SwapOffer,
  SwapPolicy,
  SwapState,
  TransferPolicy,
  WorkTier,
} from '@keicoin/core'

export {
  MAX_CLAIM_AMOUNT_DIGITS,
  MAX_CLAIM_PROOF_LENGTH,
  MAX_CLAIM_RECORD_BYTES,
  MAX_PENDING_CLAIMS,
  buildCommit,
  createBrowserClaimStore,
  createMemoryClaimStore,
} from '@keicoin/claims'
export type {
  BrowserClaimStoreOptions,
  ClaimBundle,
  ClaimResult,
  ClaimsApi,
  ClaimsOptions,
  ClaimStorageStatus,
  ClaimStore,
  ClaimStoreDiagnostic,
  ClaimStoreDiagnosticCode,
  ClaimStoreDurability,
  ClaimStoreScope,
  ClaimWebLockManager,
  ClaimWebStorage,
  CommitEntry,
  DurableClaimsApi,
  PendingClaim,
} from '@keicoin/claims'

export { MockIpfsUploader, itemSymbolFor, looksLikeItem } from '@keicoin/tokens'
export type {
  CreateItemOptions,
  ImageSource,
  IpfsUploader,
  IssueOptions,
  IssuerToken,
  Item,
  ItemCommitEntry,
  OwnedByOptions,
  PlayerToken,
  PublishedCommit,
  TokenTransfer,
} from '@keicoin/tokens'

export {
  DEFAULT_ACCOUNT_LIMIT,
  DEFAULT_CONCURRENCY,
  DEFAULT_MAX_CANDLES,
  MAX_ACCOUNTS_PER_WALK,
  MAX_CANDLES,
  MAX_CONCURRENCY,
  DEFAULT_DIRECTORY_LIMIT,
  MAX_DIRECTORY_LIMIT,
  assertMatches,
  bidPrice,
  classify,
  coverageOf,
  createDirectory,
  createMemoryMarketStorage,
  DEFAULT_MARKET_RETENTION,
  MAX_MARKET_RETENTION,
  MARKET_STORAGE_SCHEMA_VERSION,
  createMarketCatalog,
  createMarketStore,
  createAccountChainIngestor,
  DEFAULT_SUBSCRIPTION_READ_TIMEOUT,
  createAccountChainSource,
  createMarket,
  durationMs,
  emptyCoverage,
  expectationFrom,
  isAborted,
  isDirectory,
  isMarketError,
  isRace,
  mapConcurrent,
  mergeCoverage,
  priceIndex,
  readBook,
  reconcileOffers,
  resolveAccounts,
  settleable,
  toCandles,
  toUnixCandles,
  toUnixLine,
  toSeries,
  verify,
  walkAccounts,
  withCoverage,
} from '@keicoin/market'
export type {
  AcceptOptions,
  AccountDirectory,
  AccountRead,
  AccountSource,
  BidOptions,
  Book,
  BookLevel,
  BookOptions,
  Cancellation,
  Candle,
  CandleOptions,
  Change,
  Coverage,
  CoverageFailure,
  Covered,
  DirectoryOptions,
  DataCompleteness,
  DataState,
  ExactPriceRatio,
  Expectation,
  HistoryRangeOptions,
  InstrumentApi,
  InstrumentBook,
  InstrumentBookLevel,
  InstrumentHistory,
  InstrumentHistoryOptions,
  InstrumentIdentity,
  InstrumentOptions,
  InstrumentOrderOptions,
  InstrumentPricePoint,
  InstrumentSnapshot,
  InstrumentSnapshotOptions,
  InstrumentSubscribeOptions,
  InstrumentTicker,
  InstrumentUpdate,
  ListOptions,
  MarketApi,
  MarketDataSource,
  MarketErrorCode,
  MarketReadError,
  MarketOptions,
  MineOptions,
  MutableDirectory,
  ObservedRange,
  Offer,
  OfferLeg,
  OfferLife,
  OfferOptions,
  OfferState,
  PriceIndex,
  PriceSummary,
  PricePoint,
  PaginationLimitation,
  ReadOptions,
  ReconcileOptions,
  Reconciliation,
  RequestedRange,
  SellOptions,
  Series,
  SeriesOptions,
  SnapshotCoverage,
  SourceProvenance,
  StopSubscription,
  SubscriptionStatus,
  Settlement,
  Trade,
  TradeOptions,
  TimeQuality,
  UnixCandle,
  UnixLinePoint,
  Verification,
  Walk,
  AccountChainIngestRequest,
  AccountChainIngestResult,
  AccountChainIngestor,
  AccountChainIngestorOptions,
  AccountChainProvider,
  AccountChainSourceOptions,
  AnnouncementReceipt,
  CatalogPage,
  InstrumentQuery,
  MarketCatalog,
  MarketCatalogOptions,
  MarketInstrumentIdentity,
  MarketInstrumentRecord,
  MarketParticipant,
  MarketReadBudget,
  MarketDurability,
  MarketMemoryStorageCapabilities,
  MarketMemoryStorageAdapter,
  MarketRetention,
  MarketRetentionReport,
  MarketStorageAdapter,
  MarketStorageCapabilities,
  MarketStorageEnvelope,
  MarketStore,
  MarketStoreOptions,
  MaterializedPageInput,
  MaterializedPageReceipt,
  MemoryMarketStorage,
  ParticipantAnnouncement,
  ParticipantQuery,
  RejectedMarketRowInput,
  SourceCheckpointInput,
  StoredMarketCoverage,
  StoredMarketOffer,
  StoredMarketOfferInput,
  StoredOfferPage,
  StoredOfferQuery,
} from '@keicoin/market'

export {
  acceptableBy,
  assertAwardShape,
  assertRunnable,
  checkDropBinding,
  createEconomy,
  defineDropTable,
  defineDropTables,
  defineRecipe,
  defineRecipes,
  dropNonce,
  dropSalt,
  foldProof,
  isDropTable,
  isResolved,
  matchingOffers,
  publishDrop,
  rollDropTable,
  termsMatch,
  verifyAward,
} from '@keicoin/economy'
export type {
  AssetRef,
  CloseOptions,
  Drop,
  DropAward,
  DropOptions,
  DropOutcome,
  DropRoot,
  DropSpec,
  DropTable,
  DropTableSpec,
  EconomyApi,
  EconomyOptions,
  ListingOptions,
  MatchTerms,
  Odds,
  PublishedDrop,
  PlanContext,
  Plan,
  PlanAction,
  PlanOptions,
  PlanStep,
  Problem,
  Recipe,
  RecipeSpec,
  RecipeStrategy,
  ResolvedStack,
  RunBlock,
  RunOptions,
  RunResult,
  SinkPolicy,
  Stack,
  StockOptions,
  VerifiedDrop,
} from '@keicoin/economy'

export {
  canSpend,
  committedRaw,
  createCatalogue,
  createPlayerEconomy,
  movingRaw,
  toFunds,
} from '@keicoin/player-economy'
export type {
  BrowseOptions,
  BuyOptions,
  Catalogue,
  ChainFunds,
  Currency,
  Funds,
  Gift,
  GiftRequest,
  HistoryOptions,
  Listing,
  ListingRequest,
  Pending,
  PendingKind,
  PlayerEconomyApi,
  PlayerEconomyOptions,
  Purchase,
  Reconciled,
  Shelf,
  Shelves,
  ShopEvents,
  Ware,
  WareSpec,
} from '@keicoin/player-economy'

export { LocalWorkProvider, WorkServerProvider, createWorkProvider } from '@keicoin/work'
export {
  DEFAULT_ASSET_CACHE_LIMIT,
  DEFAULT_ASSET_CONCURRENCY,
  MAX_ASSET_CACHE_LIMIT,
  MAX_ASSET_CONCURRENCY,
  WalletPanel,
  createWallet,
} from '@keicoin/wallet'
export type {
  ItemHolding,
  TokenBalance,
  WalletApi,
  WalletOptions,
  WalletPanelCustody,
  WalletPanelHandle,
  WalletPanelKei,
  WalletPanelOptions,
  WalletPanelSection,
  WalletPanelTheme,
  WalletPanelThemeVars,
  WalletSummary,
} from '@keicoin/wallet'
